RRHH/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('general.urls')),
    url(r'^solicitud-empleo/', include('solicitud.urls')),
    url(r'^administrador/', include('administrador.urls')),
    url(r'^promocion-interna/', include('internas.urls')),
    url(r'^vacantes/', include('privadas.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handler404 = administrador.error_404
# handler500 = administrador.error_500


# def error_404(request):
#         data = {}
#         return render(request,'administrador/error_404.html', data)
 
# def error_500(request):
#         data = {}
#         return render(request,'administrador/error_500.html', data)

general/urls.py
from django.conf.urls import url
from general import views

urlpatterns = [
	url(r'^$', views.blog, name='blog'),
	url(r'^todas-ofertas$', views.todas_ofertas, name='todas_ofertas'),
	url(r'^ofertas-internas$', views.blog_internas, name='blog_internas'),
	
	url(r'^departamento/(?P<codigo>\d+)/$', views.filtro_depto, name='filtro_depto'),
	url(r'^aplicar-oferta/(?P<codigo>\d+)/$', views.aplicar_oferta, name='aplicar_oferta'),
	url(r'^registro$', views.registro, name='registro'),
	url(r'^mensaje/(?P<mensaje>\d+)/$', views.mensaje_page, name='mensaje_page'),
	url(r'^login/$', views.login, name='login'),
	url(r'^accounts/login/$', views.login, name='login'),
	url(r'^logout/$', views.cerrar_sesion, name='cerrar_sesion'),
	url(r'^cargarmunicipios/$', views.cargar_municipios, name='cargar_municipios'),
	url(r'^registro/dos/$', views.registro_dos, name='registro_dos'),
	url(r'^activarusuario/(?P<id>\d+)/$', views.activar_usuario, name='activar_usuario'),
	url(r'^perfil$', views.perfil, name='perfil'),
	url(r'^datos/personales$', views.datos_generales, name='datos_personales'),
	url(r'^informacion/familiar$', views.informacion_familiar, name='informacion_familiar'),
	url(r'^informacion/economica$', views.informacion_economica, name='informacion_economica'),
	url(r'^informacion/laboral$', views.informacion_laboral, name='informacion_laboral'),
	url(r'^informacion/academica$', views.informacion_academica	, name='informacion_academica'),
	url(r'^informacion/referencias$', views.referencias	, name='referencias'),
	url(r'^ediciondatosgenerales/(?P<codigo>\d+)/$', views.editar_datosgenerales, name='editar_datosgenerales'),
	url(r'^editarcuenta/(?P<codigo>\d+)/$', views.editar_cuenta, name='editar_cuenta'),
	url(r'^eliminarcuenta/(?P<codigo>\d+)/$', views.eliminar_cuenta, name='eliminar_cuenta'),
	url(r'^nuevacuenta/(?P<solicitud>\d+)/$', views.nueva_cuenta, name='nueva_cuenta'),
	url(r'^editarvivienda/(?P<solicitud>\d+)/$', views.editar_vivienda, name='editar_vivienda'),
	url(r'^editardeuda/(?P<solicitud>\d+)/$', views.editar_deuda, name='editar_deuda'),
	url(r'^editarembargo/(?P<solicitud>\d+)/$', views.editar_embargo, name='editar_embargo'),
	url(r'^editarotrainformacion/(?P<solicitud>\d+)/$', views.editar_otrainformacion, name='editar_otrainformacion'),
	url(r'^editaraspiracionlaboral/(?P<solicitud>\d+)/$', views.editar_aspiracionlaboral, name='editar_aspiracionlaboral'),
	url(r'^editarhermano/(?P<codigo>\d+)/$', views.editar_hermanos, name='editar_hermanos'),
	url(r'^createhermano/(?P<codigo>\d+)/$', views.create_hermanos, name='create_hermanos'),
	url(r'^editarhijo/(?P<codigo>\d+)/$', views.editar_hijo, name='editar_hijo'),
	url(r'^createhijo/(?P<codigo>\d+)/$', views.create_hijo, name='create_hijo'),
	url(r'^createdependiente/(?P<codigo>\d+)/$', views.create_dependiente, name='create_dependiente'),
	url(r'^updatedependiente/(?P<codigo>\d+)/$', views.update_dependiente, name='update_dependiente'),
	url(r'^updatepadre/(?P<codigo>\d+)/$', views.update_padre, name='update_padre'),
	url(r'^updatemadre/(?P<codigo>\d+)/$', views.update_madre, name='update_madre'),
	url(r'^updateconyugue/(?P<codigo>\d+)/$', views.update_conyugue, name='update_conyugue'),
	url(r'^deletehermano/(?P<codigo>\d+)/$', views.delete_hermano, name='delete_hermano'),
	url(r'^deletehijo/(?P<codigo>\d+)/$', views.delete_hijo, name='delete_hijo'),
	url(r'^deletedependiente/(?P<codigo>\d+)/$', views.delete_dependiente, name='delete_dependiente'),
	url(r'^createlaboral/$', views.create_laboral, name='create_laboral'),

	url(r'^updatelaboral/(?P<codigo>\d+)/$', views.update_laboral, name='update_laboral'),
	url(r'^deletelaboral/(?P<codigo>\d+)/$', views.delete_laboral, name='delete_laboral'),

##################################### Referencias Personales ####################################################
	url(r'^create-referencia-personal/$', views.create_referencia_personal, name='create_referencia_personal'),
	url(r'^update-referencia-personal/(?P<codigo>\d+)/$', views.update_referencia_personal, name='update_referencia_personal'),
	url(r'^delete-referencia-personal/(?P<codigo>\d+)/$', views.delete_referencia_personal, name='delete_referencia_personal'),

#################################### Referencias Laborales
	url(r'^create-referencia-laboral/$', views.create_referencia_laboral, name='create_referencia_laboral'),
	url(r'^update-referencia-laboral/(?P<codigo>\d+)/$', views.update_referencia_laboral, name='update_referencia_laboral'),
	url(r'^delete-referencia-laboral/(?P<codigo>\d+)/$', views.delete_referencia_laboral, name='delete_referencia_laboral'),
	url(r'^editar_curso/(?P<codigo>\d+)/$', views.editar_curso, name='editar_curso'),
	url(r'^configuracion/$', views.configuracion, name='configuracion'),
	url(r'^cambiarimagen/$', views.cambiar_imagen, name='cambiar_imagen'),
	url(r'^editarinfoperfil/$', views.editar_infoperfil, name='editar_infoperfil'),
	url(r'^cambiarclave/$', views.cambiar_clave, name='cambiar_clave'),
	url(r'^nuevocurso/$', views.nuevo_curso, name='nuevo_curso'),
	url(r'^nuevoestudio/$', views.nuevo_estudio, name='nuevo_estudio'),
###################################### Habilidades #######################################################
	url(r'^create-habilidades/$', views.create_habilidades, name='create_habilidades'),
	url(r'^update-habilidades/(?P<codigo>\d+)/$', views.update_habilidades, name='update_habilidades'),
	url(r'^delete-habilidades/(?P<codigo>\d+)/$', views.delete_habilidades, name='delete_habilidades'),
	url(r'^editarestudio/(?P<codigo>\d+)/$', views.editar_estudio, name='editar_estudio'),
	url(r'^eliminarcompetencia/(?P<codigo>\d+)/$', views.eliminar_competencia, name='eliminar_competencia'),
	url(r'^agregarcompetencias/$', views.agregar_competencias, name='agregar_competencias'),
###################################### IDIOMA #######################################################
	url(r'^create-idioma/$', views.create_idioma, name='create_idioma'),
	url(r'^update-idioma/(?P<codigo>\d+)/$', views.update_idioma, name='update_idioma'),
	url(r'^delete-idioma/(?P<codigo>\d+)/$', views.delete_idioma, name='delete_idioma'),
	url(r'^recuperarclave/$', views.recuperar_clave, name='recuperar_clave'),

	url(r'^CV/$', views.cambiar_cv, name='cambiar_cv'),
	url(r'^suscribirse/$', views.suscribirse, name='suscribirse'),

]

general/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from solicitud.models import Departamento, Municipio
import uuid

class Perfil(models.Model):
    cod_usuario = models.AutoField(primary_key=True, db_column='cod_usuario')
    nombre_usuario = models.CharField(max_length=200, blank=True, null=True, db_column='nombre_usuario')
    apellido_usuario = models.CharField(max_length=200, blank=True, null=True, db_column='apellido_usuario')
    cod_departamento = models.ForeignKey(Departamento, models.DO_NOTHING, db_column='cod_departamento', blank=True, null=True)
    cod_municipio = models.ForeignKey(Municipio, models.DO_NOTHING, db_column='cod_municipio', blank=True, null=True)
    sexo_usuario = models.CharField(max_length=1, blank=True, null=True, db_column='sexo_usuario')
    correo_usuario = models.CharField(max_length=50, blank=True, null=True, db_column='correo_usuario')
    direccion_usuario = models.CharField(max_length=300, blank=True, null=True, db_column='direccion_usuario')
    fecha_nacimiento = models.CharField(max_length=10, blank=True, null=True, db_column='fecha_nacimiento')
    telefono_celular = models.CharField(max_length=10, blank=True, null=True, db_column='telefono_celular')
    telefono_fijo = models.CharField(max_length=10, blank=True, null=True, db_column='telefono_fijo')
    telefono_oficina = models.IntegerField(blank=True, null=True, db_column='telefono_oficina')
    vehiculo = models.NullBooleanField(db_column='vehiculo')
    licencia = models.NullBooleanField(db_column='licencia')
    estado = models.NullBooleanField(db_column='estado')
    cod_user = models.ForeignKey(User, models.DO_NOTHING, db_column='cod_user', blank=True, null=True)
    foto_usuario = models.ImageField(upload_to='fotos/')
 
    class Meta:
        managed = False
        db_table = 'Perfil'

privadas/forms.py
#-*-coding: utf-8-*-
from django.forms import ModelForm
from django.forms.widgets import *
from django import forms
from solicitud.models import *
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User, Group

ESTADO_CIVIL = (
	('','---------'),
	('S', 'Soltero(a)'),
	('C', 'Casado(a)'),
	('U', 'Union Libre'),
	('V', 'Viudo'),
	('D', 'Divorciado'),

)

LICENCIA = (
	('', '-------------'),
	(True, 'SI'),
	(False, 'NO'),
)

AUTOMOVIL = (
	('', '-------------'),
	(True, 'SI'),
	(False, 'NO'),
)

POLIZA = (
	('', '-------------'),
	(True, 'SI'),
	(False, 'NO'),
)

DEPORTE = (
	('', '-------------'),
	(True, 'SI'),
	(False, 'NO'),
)

DEPORTES = (
	('Futbol', 'Futbol'),
	('Baloncesto', 'Baloncesto'),
	('Volibol', 'Volibol'),
	('Béisbol', 'Béisbol'),
	('Atletismo', 'Atletismo'),
	('Natación', 'Natación'),
	('Ciclismo', 'Ciclismo'),
	('Rugby', 'Rugby'),
	('Karate', 'Karate'),
	('Taekwondo', 'Taekwondo'),
	('Judo', 'Judo'),
	('Kung Fu', 'Kung Fu'),
	('Boxeo', 'Boxeo'),
	('Tenis', 'Tenis'),
	('Tenis de mesa','Tenis de mesa'),
	('Otro', 'Otro'),
)

IDIOMA = (
	('', '-----------'),
	('Ingles', 'Ingles'),
	('Aleman', 'Alemán'),
	('Frances', 'Frances'),
	('Portugues', 'Portugues'),
	('Italiano', 'Italiano'),
	('Otro', 'Otro'),
)

DEPENDENCIA_TIPO = (
	('','---------'),
	('T', 'Totalmente'),
	('P', 'Parcialmente'),
)

VIVIENDA_TIPO = (
	('', '--------'),
	('F', 'Con su familia'),
	('P', 'Propietario'),
	('I', 'Inquilino'),
	('E', 'Pensionista'),
)

DESPIDO =(
	('0', '------------'),
	('Despido', 'Despido'),
	('Renuncia', 'Renuncia'),

)

CUENTA_TIPO = (
	('', '--------'),
	('M', 'Depósitos monetarios'),
	('A', 'Depósitos de ahorro'),
	('O', 'Otros'),
)

PARENTESCO = (
	(' ', '---------'),
	('C', 'Conyugue'),
	('H', 'Hijo'),
	('I', 'Hija'),
	('P', 'Padre'),
	('M', 'Madre'),
	('F', 'Familiar'),
	('O', 'Otros'),
)

Orga = (
	(' ', '---------'),
	('Club Deportivo Olimpia', 'Club Deportivo Olimpia'),
	('Fundacion Hondureña para el niño con cancer', 'Fundacion Hondureña para el niño con cancer'),
	('Hogar diamante', 'Hogar diamante'),
	('Arca de las esperanzas', 'Arca de las esperanzas'),
)

sexo = (
	('femenino', 'Femenino'),
	('masculino', 'Masculino'),
)

NIVEL_ESTUDIO = (
	('0', '----------'),
	('1', 'PRIMARIA'),
	('2', 'SECUNDARIA'),
	('3', 'PREGRADO'),
	('4', 'POSTGRADO'),
	('5', 'DOCTORADO'),
)

class SolicitudFrm(ModelForm):
	estadocivil = forms.ChoiceField(choices=ESTADO_CIVIL, required=False, initial="Seleccione su estado civil")
	direccion_domicilio = forms.CharField( widget=forms.Textarea(attrs={'rows' : '3' ,'placeholder' : 'bloque 15, casa #...'}))
	automovil = forms.ChoiceField(choices=AUTOMOVIL, required=False)
	licencia = forms.ChoiceField(choices=LICENCIA, required=False)
	polizaseguro = forms.ChoiceField(choices=POLIZA, required=False)
	deporte = forms.ChoiceField(choices=DEPORTE, required=False)
	tipodeporte = forms.ChoiceField(choices=DEPORTES)
	hermanos = forms.ChoiceField(choices=DEPORTE, required=False)
	casado = forms.ChoiceField(choices=DEPORTE, required=False)
	hijos = forms.ChoiceField(choices=DEPORTE, required=False)
	dependientes = forms.ChoiceField(choices=DEPORTE, required=False)
	tipovivienda = forms.ChoiceField(choices=VIVIENDA_TIPO, required=False)
	cuentasbancarias = forms.ChoiceField(choices=DEPORTE, required=False)
	deudaspendientes = forms.ChoiceField(choices=DEPORTE, required=False)
	parentesco = forms.ChoiceField(choices=PARENTESCO, required=False)
	sexo = forms.ChoiceField(choices=sexo, widget=RadioSelect, required= False)
	direcciondomicilio = forms.CharField( widget=forms.Textarea(attrs={'rows' : '3' }), required=False)
	observaciones_adicionales = forms.CharField( widget=forms.Textarea(attrs={'rows' : '4'}), required=False)
	organizacion = forms.CharField( widget=forms.Textarea(attrs={'rows' : '3' }), required=False)
	domiciliopadre = forms.CharField( widget=forms.Textarea(attrs={'rows' : '3' }), required=False)
	direccionlaboralpadre = forms.CharField( widget=forms.Textarea(attrs={'rows' : '3' }), required=False)
	domiciliomadre = forms.CharField( widget=forms.Textarea(attrs={'rows' : '3' }), required=False)
	direccionlaboralmadre = forms.CharField( widget=forms.Textarea(attrs={'rows' : '3' }), required=False)
	domicilioconyugue = forms.CharField( widget=forms.Textarea(attrs={'rows' : '3' }), required=False)
	direccionlaboralconyugue = forms.CharField( widget=forms.Textarea(attrs={'rows' : '3' }), required=False)
	class Meta:
		model = Solicitud
		fields = '__all__'
		exclude = []


class HermanoFrm(ModelForm):
	domicilio = forms.CharField( widget=forms.Textarea(attrs={'rows' : '3' }), required=False)


	class Meta:
		model = Hermano
		fields = '__all__'
		exclude = []
		


class HijoFrm(ModelForm):

	nombres = forms.CharField(label="nombres", required=False )

	class Meta:
		model = Hijo
		fields = '__all__'
		exclude = []


class DependienteFrm(ModelForm):
	tipodependencia = forms.ChoiceField(choices=DEPENDENCIA_TIPO, required=False)

	class Meta:
		model = Dependiente
		fields = '__all__'
		exclude = []


class HistoriallaboralFrm(ModelForm):

	motivoretiro = forms.ChoiceField(choices=DESPIDO, required=False)
	direccionempresa = forms.CharField( widget=forms.Textarea(attrs={'rows' : '3' ,'placeholder' : 'calle los alc....'}))
	fucionespuesto = forms.CharField( widget=forms.Textarea(attrs={'rows' : '3' , 'placeholder' : 'Tareas que realizaba'}))
	class Meta:
		model = Historiallaboral
		fields = '__all__'
		exclude = []

class HistorialacademicoFrm(ModelForm):
	nivel_estudios=forms.ChoiceField(choices=(NIVEL_ESTUDIO), widget=forms.Select(attrs={'id':'select_niveles'}))
	class Meta:
		model = Historialacademico
		fields = '__all__'
		exclude = []


class CursoFrm(ModelForm):
	direccioncentroestudio = forms.CharField( widget=forms.Textarea(attrs={'rows' : '3' , 'placeholder' : ''}))

	class Meta:
		model = Curso
		fields = '__all__'
		exclude = []

class ReferenciaFrm(ModelForm):
	direccion = forms.CharField( widget=forms.Textarea(attrs={'rows' : '3' , 'placeholder' : ''}))
	class Meta:
		model = Referencia
		fields = '__all__'
		exclude = []

class ReferenciaPersonalFrm(ModelForm):
	direccion_personal = forms.CharField( widget=forms.Textarea(attrs={'rows' : '3' , 'placeholder' : ''}))

	class Meta:
		model = Referenciaspersonal
		fields = '__all__'
		exclude = []


class OrganizacionFrm(ModelForm):

	nombre = forms.ChoiceField(choices=Orga, required=False)
	seleccionadas = forms.CharField(widget=forms.Textarea(attrs={'rows' : '4' , 'readonly' :'readonly'}))
	class Meta:
		model = Organizacion
		fields = '__all__'
		exclude = []


class CuentaFrm(ModelForm):
	tipo_cuenta = forms.ChoiceField(choices=CUENTA_TIPO, required=False)

	class Meta:
		model = Cuenta
		fields = '__all__'
		exclude = []


class IdiomaFrm(ModelForm):
	nombre= forms.ChoiceField(choices=IDIOMA, required=False, widget=Select(attrs={'id':'select_idioma'}))
	class Meta:
		model = Idioma
		fields = '__all__'
		exclude = []

HABILIDADES = (
	('00', '----------'),
	('01', 'DISEÑO GRÁFICO'),
	('02', 'PROGRAMACIÓN'),
	('03', 'OFFICE'),
	('04', 'SOPORTE TÉCNICO'),
	('05', 'REDES E INFRAESTRUCTURA'),
)

class HabilidadFrm(ModelForm):
	nombre_habilidad = forms.ChoiceField(choices=HABILIDADES, widget=Select(attrs={'id':'select_habilidades'}))
	class Meta:
		model = Habilidad
		fields = '__all__'
		exclude = []

general/templates/create-laboral.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="col-lg-9">
	<form  method="POST" accept-charset="utf-8"  action="">
	    {% csrf_token %}
	    <div id="esta_trabajando">
	        <label for="chck1" style="font-weight: 600;">¿Es tu empleo actual?</label><br>
	        <label class="form-check-inline u-check g-mr-20 mx-0 mb-0" >
	        <input class="hidden-xs-up g-pos-abs g-top-0 g-right-0 chck1" name="trabajoactual" type="checkbox" id="chck1" value="False" >
	        <div class="u-check-icon-radio-v7">
	          <i class="fa" data-check-icon="" data-uncheck-icon=""></i>
	        </div>
	      </label>
	     <br><br>
	        <div class="row">
	          <div class="col-xs-12 col-sm-4 mb-4">
	            <label style="font-weight: normal;">Nombre de empresa:</label>
	            <input type="text" name="nombreempresa" id="id_nombreempresa" value="">
	          </div>
	          <div class="form-group col-xs-12 col-sm-4 mb-4">
	            <label style="font-weight: normal;" for="id_fechaingreso">Fecha ingreso</label>
	            <div class="input-group g-brd-primary--focus">
	            	<input type="text" name="fechaingreso" id="id_fechaingreso" value="{{histo.fechaingreso}}">
	              <div class="input-group-addon d-flex align-items-center g-bg-white g-color-gray-dark-v5 rounded-0">
	                <i class="icon-calendar"></i>
	              </div>
	            </div>
	          </div>
	          <div class="form-group col-xs-12 col-sm-4 mb-4 actual">
	            <label style="font-weight: normal;" for="id_fechaegreso">Fecha egreso</label>
	            <div class="input-group g-brd-primary--focus">
	            	<input type="text" name="fechaegreso" id="id_fechaegreso" value="{{histo.fechaegreso}}">
	              <div class="input-group-addon d-flex align-items-center g-bg-white g-color-gray-dark-v5 rounded-0">
	                <i class="icon-calendar"></i>
	              </div>
	            </div>
	          </div>
	        </div>

	        <div class="row">
	          <div class="col-xs-12 col-sm-4 mb-4">
	            <label style="font-weight: normal;">Dirección:</label>
	            <textarea name="direccionempresa" rows="3" id="id_direccionempresa"></textarea>
	          </div>

	          <div class="col-xs-12 col-sm-4 mb-4">
	            <label style="font-weight: normal;">Nombre jefe inmediato:</label>
	            <input type="text" name="nombrejefeinmediato" id="id_nombrejefeinmediato" value="">
	          </div>
	          <div class="col-xs-12 col-sm-4 mb-4 actual">
	            <label style="font-weight: normal;">Motivo retiro:</label>
	            {{historial.motivoretiro}}
	          </div>
	        </div>
	    </div>
	    <br><br>
	    <hr class="g-brd-gray-light-v4 g-mx-minus-30">

	    <div class="col-12 align-self-center text-right">
	      <a href="{% url 'informacion_laboral' %}" class="btn btn-md u-btn-indigo  rounded g-py-13 g-px-25" style="margin-right: 5px;">Cancelar</a>
	      <button type="submit" class="btn btn-md u-btn-primary rounded g-py-13 g-px-25">Guardar cambios</button>
	    </div>
    </form>
</div>

{% endblock content %}
{% block javascript %}
<script>
	$(document).ready(function() {
    	$("#id_nombreempresa, #id_fechaingreso, #id_direccionempresa, #id_nombrejefeinmediato,#id_salariofinal, #id_puesto , #id_salarioinicial, #id_horario , #id_horainicio, #id_horasalida, #id_fucionespuesto").attr("required", true);


		if($(".chck1").val() =="True"){
			$('.actual').hide();
			$("#id_fechaegreso").attr('value', '');
		}
		else{
			$('.actual').show();

		}


		if($(".sabado").val() =="True"){
			$('.sab').show();
		}
		else{
			$('.sab').hide();
			$("#id_horainiciosabado , #id_horasalidasabado").attr('value', '');
		}


	     $(' input[name="fechaingreso"], input[name="fechaegreso"] ' ).datepicker({
	      autoclose: true,
	      format: 'yyyy-mm-dd',
	      language: 'es',
	    });

	 	$(".chck1").change(function(){
	    	if ($(this).val() == "True") {
		      	$(this).attr('value', 'False')
		      	$('.actual').show();
	    	}
	    	else{
	      	$(this).attr('value', 'True')

	      		$('.actual').hide();
		      	$("#id_fechaegreso").attr('value', '');

		      	$("#id_motivoretiro option[value='0']").attr('selected','selected');
		      	$('#id_motivoretiro').select2({
		          theme:'bootstrap',
		          width: '100%'
		        });
	    	}
	 	});

	 	$(".sabado").change(function(){
	    	if ($(this).val() == "True") {
	      	$(this).attr('value', 'False')
	      	$('.sab').hide();
	      	$("#id_horainiciosabado , #id_horasalidasabado").attr('value', '');


	    	}
	    	else{
	      	$(this).attr('value', 'True')
	      	$('.sab').show();
	    	}
	 	});

	});
	$(document).ready(function(){
		$('#sidemenu a').each(function(){
			$(this).removeClass();
			$(this).addClass('list-group-item list-group-item-action justify-content-between');
		});
		$('#trabajo').addClass('list-group-item list-group-item-action justify-content-between active');
	});
</script>
{% endblock javascript %}