RRHH/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('general.urls')),
    url(r'^solicitud-empleo/', include('solicitud.urls')),
    url(r'^administrador/', include('administrador.urls')),
    url(r'^promocion-interna/', include('internas.urls')),
    url(r'^vacantes/', include('privadas.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handler404 = administrador.error_404
# handler500 = administrador.error_500


# def error_404(request):
#         data = {}
#         return render(request,'administrador/error_404.html', data)
 
# def error_500(request):
#         data = {}
#         return render(request,'administrador/error_500.html', data)

solicitud/urls.py
from django.conf.urls import url
from solicitud import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^ajax_departamento/$', views.ajax_departamento, name='ajax_departamento'),
	url(r'^ajax_municipio/$', views.ajax_municipio, name='ajax_municipio'),
	url(r'^ajax_municipios_pais/$', views.ajax_municipios_pais, name='ajax_municipios_pais'),
	url(r'^ajax_hermanos/$', views.ajax_hermanos, name='ajax_hermanos'),
	url(r'^ajax_cargarorgs/$', views.ajax_cargarorgs, name='ajax_cargarorgs'),
	url(r'^ajax_adicionarorg/$', views.ajax_adicionarorg, name='ajax_adicionarorg'),
	url(r'^ajax_escuelas/$', views.ajax_escuelas, name='ajax_escuelas'),
	url(r'^ajax_colegios/$', views.ajax_colegios, name='ajax_colegios'),
	url(r'^ajax_universidades/$', views.ajax_universidades, name='ajax_universidades'),
	url(r'^ajax_campus/$', views.ajax_campus, name='ajax_campus'),
	url(r'^ajax_carreras/$', views.ajax_carreras, name='ajax_carreras'),
	url(r'^solicitud_1/(?P<codigo>\d+)$', views.solicitud_1, name='solicitud_1'),
	url(r'^solicitud_2/(?P<codigo>\d+)$', views.solicitud_2, name='solicitud_2'),
	url(r'^solicitud_3/(?P<codigo>\d+)$', views.solicitud_3, name='solicitud_3'),
	url(r'^solicitud_4/(?P<codigo>\d+)$', views.solicitud_4, name='solicitud_4'),
	url(r'^no_historial_laboral/$', views.no_historial_laboral, name='no_historial_laboral'),
	url(r'^solicitud_5/(?P<codigo>\d+)$', views.solicitud_5, name='solicitud_5'),
	url(r'^solicitud_6/(?P<codigo>\d+)$', views.solicitud_6, name='solicitud_6'),
]

solicitud/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class Campus(models.Model):
    cod_campus = models.AutoField(db_column='Cod_campus', primary_key=True)  # Field name made lowercase.
    cod_universidad = models.ForeignKey('Universidad', models.DO_NOTHING, db_column='Cod_universidad', blank=True, null=True)  # Field name made lowercase.
    nombre = models.CharField(db_column='Nombre', max_length=100, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Sol].[Campus'


class Carrera(models.Model):
    cod_carreras = models.AutoField(db_column='Cod_carreras', primary_key=True)  # Field name made lowercase.
    cod_campus = models.ForeignKey('Universidad', models.DO_NOTHING, db_column='Cod_campus', blank=True, null=True)  # Field name made lowercase.
    nombre_carrera = models.CharField(db_column='Nombre_carrera', max_length=200, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Sol].[Carreras'


class CarrerasSolicitud(models.Model):
    cod_solicitud = models.ForeignKey('Solicitud', models.DO_NOTHING, db_column='Cod_solicitud')  # Field name made lowercase.
    cod_universidad = models.IntegerField(db_column='Cod_universidad')  # Field name made lowercase.
    cod_campus = models.IntegerField(db_column='Cod_campus')  # Field name made lowercase.
    cod_carrera = models.ForeignKey(Carrera, models.DO_NOTHING, db_column='Cod_carrera')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Sol].[Carreras_Solicitud'
        unique_together = (('cod_solicitud', 'cod_carrera'),)


class Colegio(models.Model):
    cod_colegios = models.AutoField(db_column='Cod_Colegios', primary_key=True)  # Field name made lowercase.
    nombre = models.CharField(db_column='Nombre', max_length=300, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Sol].[Colegios'


class Competencia(models.Model):
    cod_compentencias = models.AutoField(db_column='Cod_compentencias', primary_key=True)  # Field name made lowercase.
    cod_solicitud = models.ForeignKey('Solicitud', models.DO_NOTHING, db_column='Cod_solicitud', blank=True, null=True)  # Field name made lowercase.
    nombre_competencia = models.CharField(db_column='Nombre_competencia', max_length=50, blank=True, null=True)  # Field name made lowercase.
    posee = models.NullBooleanField(db_column='Posee')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Sol].[Competencias'


class Cuenta(models.Model):
    cod_cuenta = models.AutoField(db_column='Cod_cuenta', primary_key=True)  # Field name made lowercase.
    cod_solicitud = models.ForeignKey('Solicitud', models.DO_NOTHING, db_column='Cod_solicitud', blank=True, null=True)  # Field name made lowercase.
    tipo_cuenta = models.CharField(db_column='Tipo_cuenta', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cantidad = models.DecimalField(db_column='Cantidad', max_digits=18, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    institucion = models.CharField(db_column='Institucion', max_length=50, blank=True, null=True)  # Field name made lowercase.
    numero_cuenta = models.TextField(db_column='Numero_cuenta', blank=True, null=True)  # Field name made lowercase.
    class Meta:
        managed = False
        db_table = 'Sol].[Cuentas'


class Curso(models.Model):
    codcurso = models.AutoField(db_column='CodCurso', primary_key=True)  # Field name made lowercase.
    codsolicitud = models.ForeignKey('Solicitud', models.DO_NOTHING, db_column='CodSolicitud', blank=True, null=True)  # Field name made lowercase.
    temacurso = models.CharField(db_column='TemaCurso', max_length=100, blank=True, null=True)  # Field name made lowercase.
    nombrecentroestudio = models.CharField(db_column='NombreCentroEstudio', max_length=100, blank=True, null=True)  # Field name made lowercase.
    direccioncentroestudio = models.TextField(db_column='DireccionCentroEstudio', blank=True, null=True)  # Field name made lowercase.
    duracion = models.CharField(db_column='Duracion', max_length=50, blank=True, null=True)  # Field name made lowercase.
    titulo = models.CharField(db_column='Titulo', max_length=100, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Sol].[Cursos'

 
class Departamento(models.Model):
    coddepartamento = models.AutoField(db_column='CodDepartamento', primary_key=True)  # Field name made lowercase.
    codpais = models.ForeignKey('Pais', models.DO_NOTHING, db_column='CodPais', blank=True, null=True)  # Field name made lowercase.
    descripciondepartamento = models.CharField(db_column='DescripcionDepartamento', max_length=50, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Sol].[Departamentos'

class Dependiente(models.Model):
    coddependiente = models.AutoField(db_column='CodDependiente', primary_key=True)  # Field name made lowercase.
    codsolicitud = models.ForeignKey('Solicitud', models.DO_NOTHING, db_column='CodSolicitud', blank=True, null=True)  # Field name made lowercase.
    nombredependiente = models.CharField(db_column='NombreCompleto', max_length=100, blank=True, null=True)  # Field name made lowercase.
    tipodependencia = models.CharField(db_column='TipoDependencia', max_length=1, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Sol].[Dependientes'

class Escuela(models.Model):
    cod_escuelas = models.IntegerField(db_column='Cod_escuelas', primary_key=True)  # Field name made lowercase.
    nombre = models.CharField(db_column='Nombre', max_length=300, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Sol].[Escuelas'

class Habilidad(models.Model):
    cod_habilidad = models.AutoField(db_column='Cod_habilidad', primary_key=True)  # Field name made lowercase.
    cod_solicitud = models.ForeignKey('Solicitud', models.DO_NOTHING, db_column='Cod_solicitud', blank=True, null=True)  # Field name made lowercase.
    nombre_habilidad = models.CharField(db_column='Nombre_habilidad', max_length=50, blank=True, null=True)  # Field name made lowercase.
    porcentaje = models.IntegerField(db_column='Porcentaje', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Sol].[Habilidades'

class Hermano(models.Model):
    codhermano = models.AutoField(db_column='CodHermano', primary_key=True)  # Field name made lowercase.
    codsolicitud = models.ForeignKey('Solicitud', models.DO_NOTHING, db_column='CodSolicitud', related_name="hermano_solicitud", blank=True, null=True)  # Field name made lowercase.
    nombrecompleto = models.CharField(db_column='NombreCompleto', max_length=100, blank=True, null=True)  # Field name made lowercase.
    edad = models.IntegerField(db_column='Edad', blank=True, null=True)  # Field name made lowercase.
    domicilio = models.TextField(db_column='Domicilio',  blank=True, null=True)  # Field name made lowercase.
    telefono = models.CharField(db_column='Telefono', max_length=10, blank=True, null=True)  # Field name made lowercase.
    ocupacion = models.CharField(db_column='Ocupacion', max_length=100, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Sol].[Hermanos'

class Hijo(models.Model):
    codhijo = models.AutoField(db_column='CodHijo', primary_key=True)  # Field name made lowercase.
    codsolicitud = models.ForeignKey('Solicitud', models.DO_NOTHING, db_column='CodSolicitud', blank=True, null=True)  # Field name made lowercase.
    nombreshijo = models.CharField(db_column='Nombres', max_length=100, blank=True, null=True)  # Field name made lowercase.
    apellidoshijo = models.CharField(db_column='Apellidos', max_length=100, blank=True, null=True)  # Field name made lowercase.
    edadhijo = models.IntegerField(db_column='Edad', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Sol].[Hijos'

class Historialacademico(models.Model):
    codinstitucion = models.AutoField(db_column='CodInstitucion', primary_key=True)
    codsolicitud = models.ForeignKey('Solicitud', models.DO_NOTHING, db_column='CodSolicitud', blank=True, null=True)  # Field name made lowercase.
    nombreinstitucion = models.CharField(db_column='NombreInstitucion', max_length=50, blank=True, null=True)  # Field name made lowercase.
    nivelestudios = models.CharField(db_column='NivelEstudios', max_length=100, blank=True, null=True)  # Field name made lowercase.
    lugarestudio = models.CharField(db_column='LugarEstudio', max_length=100, blank=True, null=True)  # Field name made lowercase.
    tituloobtenido = models.CharField(db_column='TituloObtenido', max_length=100, blank=True, null=True)  # Field name made lowercase.
    inicio = models.IntegerField(db_column='Inicio', null=True, blank=True)
    fin = models.IntegerField(db_column='Fin', null=True, blank=True)

    class Meta:
        managed = False
        db_table = 'Sol].[HistorialAcademico'
  
class Historiallaboral(models.Model):
    codempresa = models.AutoField(db_column='CodEmpresa', primary_key=True)
    codsolicitud = models.ForeignKey('Solicitud', models.DO_NOTHING, db_column='CodSolicitud', blank=True, null=True)  # Field name made lowercase.
    nombreempresa = models.CharField(db_column='NombreEmpresa', max_length=50, blank=True, null=True)  # Field name made lowercase.
    fechaingreso = models.CharField(db_column='FechaINgreso', max_length=10, blank=True, null=True)  # Field name made lowercase.

solicitud/templates/div_copias.html
<div id="hermano_copia" style="display: none;">
  <hr class="g-brd-gray-light-v4 g-mx-minus-30">
  <div class="row">
    <div class="col-xs-12 col-sm-4 mb-4">
      <label style="font-weight: normal;">Nombre completo: <b style="color:red;">*</b> </label>
      <input type="text" name="nombrecompleto[]" id="id_nombrecompleto" class="soloLetras" maxlength="100">
    </div>
    <div class="col-xs-12 col-sm-4 mb-4">
      <label style="font-weight: normal;">Edad:</label> 
      <input type="number" name="edad[]" id="id_edad">
    </div>

    <div class="col-xs-12 col-sm-4 mb-4" id="clonar">
      <label style="font-weight: normal;">Profesión u Oficio:</label>
      <input type="text" name="ocupacion[]" maxlength="100" id="id_ocupacion">
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-4 mb-4">
      <label style="font-weight: normal;">Celular:</label>
      <input type="text" name="telefono[]" id="id_telefono" maxlength="10">
    </div>
      
    <div class="col-xs-12 col-sm-4 mb-4">
      <label style="font-weight: normal;">Domicilio:</label>
      <textarea name="domicilio[]" id="id_domicilio" maxlength="200" rows="3"></textarea>
    </div>

    <div class="col-xs-12 col-sm-4 mb-4">
      <div class="col-12 align-self-center text-right">
      <br>
        <button  type="button" class="btn btn-outline-danger u-btn-info eliminar" id="eliminar">
          Eliminar</button>
        </div>
      </div>
  </div>
</div> 
<div id="hijo_copia" style="display: none;">
  <hr class="g-brd-gray-light-v4 g-mx-minus-30">
  <div class="row">
    <div class="col-xs-12 col-sm-4 mb-4">
      <label style="font-weight: normal;">Nombres: <b style="color:red;">*</b> </label>
      <input type="text" name="nombreshijo[]" id="id_nombreshijo" class="soloLetras" maxlength="100">
    </div>
    <div class="col-xs-12 col-sm-4 mb-4">
      <label style="font-weight: normal;">Apellidos: <b style="color:red;">*</b> </label>
      <input type="text" name="apellidoshijo[]" id="id_apellidoshijo" class="soloLetras" maxlength="100">
    </div>
    <div class="col-xs-12 col-sm-4 mb-4">
      <label style="font-weight: normal;">Edad:</label>
      <input type="number" name="edadhijo[]" id="id_edadhijo">
    </div>
  </div>
  <div class="row" style="text-align: left;">
    <div class="col-12 align-self-center text-right">
      <button  type="button" class="btn btn-outline-danger u-btn-info eliminar_hijo" id="eliminar_hijo">Eliminar</button>
    </div>
  </div>
</div>
<div id="dependiente_copia" style="display: none;">
  <hr class="g-brd-gray-light-v4 g-mx-minus-30">
  <div class="row">
    <div class="col-xs-12 col-sm-4 mb-4">
      <label style="font-weight: normal;">Nombre Completo:</label>
      <input type="text" name="nombredependiente" id="id_nombredependiente" class="soloLetras" maxlength="100">
    </div>
    <div class="col-xs-12 col-sm-4 mb-4">
      <label style="font-weight: normal;">Tipo de dependencia:</label>
      {{depen.tipodependencia}}
    </div>
    <div class="col-xs-12 col-sm-4 mb-4">
      <div class="col-12 align-self-center text-right">
        <br>
        <button  type="button" class="btn btn-outline-danger u-btn-info rounded eliminar_dependiente" id="eliminar_dependiente">Eliminar</button>
      </div>
    </div>
  </div>
</div>

solicitud/templates/error_alert.html
<div class="row">
  <div class="col-lg-6">
    <!-- Yellow Alert -->
    <div class="alert alert-dismissible fade show g-bg-yellow rounded-0" role="alert">
      <button type="button" class="close u-alert-close--light" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <div class="media">
    <span class="d-flex g-mr-10 g-mt-5">
      <i class="icon-info g-font-size-25"></i>
    </span>
        <span class="media-body align-self-center">
      <strong>Oups!</strong> Algo salio mal por favor intenta de nuevo.
    </span>
      </div>
    </div>
    <!-- End Yellow Alert -->
  </div>
</div>

solicitud/templates/solicitud_4.html
{% extends "basesolicitud.html" %}
{% load staticfiles %}
{% block content %}
<section class="g-bg-gray-light-v5">
  <div class="container g-py-30">
    <div class="row justify-content-center">
      <div class="col-sm-10 col-md-9 col-lg-12">
        <div class="u-shadow-v25 g-bg-white rounded g-py-30 g-px-25">
          <header class="text-center mb-4">
            <h4 class="h4 g-color-black g-font-weight-400">INGRESO DE INFORMACIÓN</h4>
          </header>
          <hr class="g-brd-gray-light-v4 g-mx-minus-30">
          {% if error %}
            {% include 'error_alert.html' %}
          {% endif %}
          <label> <b style="font-weight: bold;"> IV. HISTORIAL LABORAL <b> </label>
            <div class="row">
            <div class="col-xs-12 col-sm-6 mb-6" >
              <label style="font-weight: 600;" for="">No tengo historial laboral:</label>
              <a href="{% url 'no_historial_laboral' %}" class="btn btn-sm u-btn-primary "> Saltar este paso</a>
            </div>
          </div> <br>
          {% include 'includes/div_add_historial_lab.html' %}
          <!-- Form -->
         <form  class="g-py-30" method="POST" accept-charset="utf-8" id="form_solicitud4">
            {% csrf_token %}
            <div class="esta_trabajando">
              <div class="row">
                <div  style="margin-top: 3px !important; margin-left:12px; ">
                  <label for="chck1" style="font-weight: 600;">Selecciona si es tu empleo actual:</label>
                </div>
                <div clas.s="col-xs-12 col-sm-6 mb-6">
                  <label class="form-check-inline u-check g-mr-20 mx-0 mb-0" style="">
                    <input class="hidden-xs-up g-pos-abs g-top-0 g-right-0 chck1" name="trabajoactual[]" type="checkbox" id="chck1" value="False">
                    <div class="u-check-icon-radio-v7">
                      <i class="fa" data-check-icon="" data-uncheck-icon=""></i>
                    </div>
                  </label>
                </div>
              </div> 
              <div class="row">
                <div class="col-xs-12 col-sm-4 mb-4">
                  <label class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">Nombre de empresa: <b style="color:red;">*</b></label>
                  <input type="text" name="nombreempresa[]" id="id_nombreempresa" required="" maxlength="50">
                </div>
                <div class="form-group col-xs-12 col-sm-4 mb-4 casi">
                  <label class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13" for="id_fechanacimiento" id="fechaca">Fecha ingreso: <b style="color:red;">*</b></label>
                  <div class="input-group g-brd-primary--focus">
                  <input type="text" name="fechaingreso[]" id="id_fechaingreso" required="" class="dates">
                    <div class="input-group-addon d-flex align-items-center g-bg-white g-color-gray-dark-v5 rounded-0">
                      <i class="icon-calendar"></i>
                    </div>
                  </div>
                </div>
                <div class="form-group col-xs-12 col-sm-4 mb-4 esta">
                  <label  class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13" for="id_fechanacimiento">Fecha egreso: <b style="color:red;">*</b></label>
                  <div class="input-group g-brd-primary--focus">
                    <input type="text" name="fechaegreso[]" id="id_fechaegreso" required="" class="dates is_trab_actual">
                    <div class="input-group-addon d-flex align-items-center g-bg-white g-color-gray-dark-v5 rounded-0">
                      <i class="icon-calendar"></i>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-xs-12 col-sm-4 mb-4">
                  <label class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">Puesto: <b style="color:red;">*</b></label>
                  <input type="text" name="puesto[]" id="id_puesto" required maxlength="100">
                </div>
                <div class="form-group col-xs-12 col-sm-4 mb-4">
                  <label class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13" >Funciones del puesto: <b style="color:red;">*</b></label>
                  <div class="input-group g-brd-primary--focus">
                    <textarea name="fucionespuesto[]" id="id_fucionespuesto" maxlength="100" required></textarea>
                  </div>
                </div>
                <div class="form-group col-xs-12 col-sm-4 mb-4">
                    <label class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13" >Salario: <b style="color:red;">*</b></label>
                    <div class="input-group g-brd-primary--focus casi">
                      <input type="number" step="0.01" name="salariofinal[]" id="id_salariofinal">
                    </div>
                </div>
              </div> 
              <div class="row">
                <div class="col-xs-12 col-sm-4 mb-4">
                  <label  class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">Dirección: <b style="color:red;">*</b></label>
                  <textarea name="direccionempresa[]" id="id_direccionempresa" required maxlength="200"></textarea>
                </div>
                <div class="col-xs-12 col-sm-4 mb-4">
                  <label  class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">Nombre jefe inmediato: <b style="color:red;">*</b></label>
                  <input type="text" name="nombrejefeinmediato[]" maxlength="200" required="" id="id_nombrejefeinmediato">
                </div>
                <div class="col-xs-12 col-sm-4 mb-4 motivopor">
                  <label  class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">Motivo retiro: <b style="color:red;">*</b></label>
                  <select name="motivoretiro[]" id="id_motivoretiro" required class="is_trab_actual">
                    <option value="">------------</option>
                    <option value="Despido">Despido</option>
                    <option value="Renuncia">Renuncia</option>
                  </select>
                </div>
              </div>
            </div>
            <div class="row" style="text-align: left;">
              <div class="col-12 align-self-center text-right">
                <button  type="button" class="btn btn-outline-info u-btn-info" id="agregar_laboral">Nuevo historial laboral</button>
              </div>
            </div>
            <div class="nueva_laboral">
            </div>
            <br><br>
            <hr class="g-brd-gray-light-v4 g-mx-minus-30">
            <div class="row" style="text-align: center; display: block;">
              <label><b>4 de 6</b></label>
            </div>
            <div class="col-12 align-self-center text-right">
              <a href="{% url 'perfil' %}" class="btn btn-secondary" style="margin-right: 5px;">Salir</a>
              <button type="submit" class="btn btn-primary">Siguiente</button>
            </div>
          </form>
          <!-- End Form -->
        </div>
      </div>
    </div>
  </div>
</section> 
{% endblock content %}
{% block javascript %}
  <!--    SCRIPT PARA INICIAR PLUGINS DE  LA PLANTILLA     -->
    <script>
      $(document).on('ready', function(){
        $.HSCore.components.HSTabs.init('[role="tablist"]');
        $.HSCore.helpers.HSFocusState.init();
        $.HSCore.components.HSCountQty.init('.js-quantity');
        $.HSCore.components.HSMaskedInput.init('[data-mask]');  
      });
      
      $(window).on('load', function () {
        // initialization of header
        $.HSCore.components.HSHeader.init($('#js-header'));
        $.HSCore.helpers.HSHamburgers.init('.hamburger');
        // initialization of HSMegaMenu component
        $('.js-mega-menu').HSMegaMenu({
          event: 'hover',
          pageContainer: $('.container'),
          breakpoint: 991
        });
      });

      $(window).on('resize', function () {
        setTimeout(function () {
          $.HSCore.components.HSTabs.init('[role="tablist"]');
        }, 200);
      });
    </script>
  <!-- ++++++++++++++++++++++ FIN ++++++++++++++++++++++++ -->

  <!--        SCRIPT PARA INICIAR PLUGINS EXTERNOS         -->
    <script>
      $(document).on('ready', function(){
        $('select').select2({
          theme:'bootstrap',
          width: '100%'
        });
        $("#form_solicitud4").validate();
        $('*').bind("cut copy paste",function(e) {
          e.preventDefault();
        });
        $(' input[name="fechaingreso[]"], input[name="fechaegreso[]"] ' ).datepicker({
          autoclose: true,
          format: 'yyyy-mm-dd',
          language: 'es',
        });

      });
    </script>
  <!-- ++++++++++++++++++++++ FIN ++++++++++++++++++++++++ -->

  <!-- SCRIPT PARA ASIGNAR MASCARAS Y PLACEHOLDER A INPUTS -->
    <script>
      $(document).on('ready', function(){
        $("input").addClass( "form-control rounded-0 u-form-control " );
        $("textarea").addClass( "form-control rounded-0 u-form-control g-resize-none" );
        $(".dates ").addClass("form-control form-control-md u-datepicker-v1 g-brd-right-none rounded-0");

      });
    </script>
  <!-- ++++++++++++++++++++++ FIN ++++++++++++++++++++++++ -->

  <!-- SCRIPT PARA MANEJAR SI EXPERIENCIA ES TRABAJO ACTUAL -->
    <script>
      $(document).ready(function() {
        $(document).on('change', '.chck1', function(){
          if ($(this).is(':checked')){
            $(this).closest('div.esta_trabajando').find('.is_trab_actual').each(function(){
              if($(this).is('select')){
                $(this).empty();
                $(this).append("<option value=''>------------</option>");
                $(this).trigger("chosen:updated");
                //$(this).prop("selectedIndex", 0).change();
                $(this).prop('required',false);
                //$(this).prop('disabled', true);
              }else{ 
                $(this).val('');
                $(this).prop('required',false);
                $(this).prop('readonly', true);
              }
            });
          }else{
            $(this).closest('div.esta_trabajando').find('.is_trab_actual').each(function(){

              if($(this).is('select')){
                $(this).prop('required',true);
                $(this).empty();
                $(this).append("<option value=''>------------</option>");
                $(this).append('<option value="Despido">Despido</option>');
                $(this).append('<option value="Renuncia">Renuncia</option>');
                $(this).trigger("chosen:updated");

              }else{
                $(this).prop('required',true);
                $(this).prop('readonly', false);
              }

            });
          }
        }); 
 
        $('#agregar_laboral').click(function(){
          $('select').select2('destroy'); 
          $this = $('#laboral_copia').clone().removeAttr('style').appendTo( '.nueva_laboral' );
          $('html, body').animate({scrollTop: $($this).offset().top}, 1000);


          $('.eliminar_laboral').click(function(){
            var id = $(this).closest("div#laboral_copia").remove();
          });
          $(' input[name="fechaingreso[]"], input[name="fechaegreso[]"] ' ).datepicker({
            autoclose: true,
            format: 'yyyy-mm-dd',
            language: 'es',
          });
          $('select[name=motivoretiro]').attr('name', 'motivoretiro[]')
          $('select').select2({
            theme:'bootstrap',
                width: '100%'
          });
        });
      });
    </script>
  <!-- ++++++++++++++++++++++ FIN ++++++++++++++++++++++++ -->
{% endblock javascript %}